services:
  postgres:
    image: postgres:13
    container_name: url-shortner-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortner_db
    ports:
      - "25432:5432"